// generated by stringer -type=Token; DO NOT EDIT

package parser

import "fmt"

const _Token_name = "UnknownEOFCommentIdentIntFloatImaginaryStringAddSubMulDivRemPowAndOrEqualLessGreaterAssignNotNotEqualLessEqualGreaterEqualIncDecAddAssignSubAssignMulAssignDivAssignRemAssignPowAssignDefinePackageImportFuncReturnSwitchCaseDefaultFallthroughConstIfElseForRangeContinueBreakGotoGoFrameMapStructType"

var _Token_index = [...]uint16{0, 7, 10, 17, 22, 25, 30, 39, 45, 48, 51, 54, 57, 60, 63, 66, 68, 73, 77, 84, 90, 93, 101, 110, 122, 125, 128, 137, 146, 155, 164, 173, 182, 188, 195, 201, 205, 211, 217, 221, 228, 239, 244, 246, 250, 253, 258, 266, 271, 275, 277, 282, 285, 291, 295}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
